name: Example CI Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  set-pending-status:
    runs-on: ubuntu-latest
    steps:
    - name: Set PR status to pending
      env:
        GITHUB_TOKEN: ${{ secrets.LPMKDIR }}
        COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
      run: |
        curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
             -H "Accept: application/vnd.github.v3+json" \
             "https://api.github.com/repos/${{ github.repository }}/statuses/$COMMIT_SHA" \
             -d '{"state": "pending", "context": "ci-workflow", "description": "Waiting for remote checks..."}'

  trigger-lambda:
    needs: set-pending-status
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Lambda Function
      run: |
        curl -X POST -m 10 "https://mjz5hfy5zxd3exs6lfavnwapbu0kqywr.lambda-url.eu-north-1.on.aws/" \
             -d '{"trigger": "start e2e tests", "pr_id": "${{ github.event.pull_request.number }}"}' &
