name: Lambda Results Handler

on:
  repository_dispatch:
    types: [lambda-test-results]

jobs:
  process-lambda-results:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Process Results
      run: |
        echo "Event Type: ${{ github.event.action }}"
        echo "Test Results: ${{ github.event.client_payload.results }}"

